[package]
name = "fuzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afl = "0.12.4"
lazy_static = "1.4.0"
memento = { version = "0.1.0", path = ".." }
